language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  matrix:
    # - JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("BayesianNetworks"))`); Pkg.pin("BayesianNetworks"); Pkg.resolve();'
  - julia -e 'using BayesianNetworks; @assert isdefined(:BayesianNetworks); @assert typeof(BayesianNetworks) === Module'
  - julia test/runtests.jl
